// Code generated by gobind. DO NOT EDIT.

// Package main is an autogenerated binder stub for package shell.
//
//   autogenerated by gobind -lang=go command-line-arguments
package main

/*
#include <stdlib.h>
#include <stdint.h>
#include "seq.h"
#include "shell.h"

*/
import "C"

import (
	"command-line-arguments"
	_seq "golang.org/x/mobile/bind/seq"
)

// suppress the error if seq ends up unused
var _ = _seq.FromRefNum

//export proxyshell_RequestBuilder_Argument
func proxyshell_RequestBuilder_Argument(refnum C.int32_t, param_arg C.nstring) {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*shell.RequestBuilder)
	_param_arg := decodeString(param_arg)
	v.Argument(_param_arg)
}

//export proxyshell_RequestBuilder_BodyBytes
func proxyshell_RequestBuilder_BodyBytes(refnum C.int32_t, param_body C.nbyteslice) {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*shell.RequestBuilder)
	_param_body := toSlice(param_body, false)
	v.BodyBytes(_param_body)
}

//export proxyshell_RequestBuilder_BodyString
func proxyshell_RequestBuilder_BodyString(refnum C.int32_t, param_body C.nstring) {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*shell.RequestBuilder)
	_param_body := decodeString(param_body)
	v.BodyString(_param_body)
}

//export proxyshell_RequestBuilder_BoolOptions
func proxyshell_RequestBuilder_BoolOptions(refnum C.int32_t, param_key C.nstring, param_value C.char) {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*shell.RequestBuilder)
	_param_key := decodeString(param_key)
	_param_value := param_value != 0
	v.BoolOptions(_param_key, _param_value)
}

//export proxyshell_RequestBuilder_ByteOptions
func proxyshell_RequestBuilder_ByteOptions(refnum C.int32_t, param_key C.nstring, param_value C.nbyteslice) {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*shell.RequestBuilder)
	_param_key := decodeString(param_key)
	_param_value := toSlice(param_value, false)
	v.ByteOptions(_param_key, _param_value)
}

//export proxyshell_RequestBuilder_Header
func proxyshell_RequestBuilder_Header(refnum C.int32_t, param_name C.nstring, param_value C.nstring) {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*shell.RequestBuilder)
	_param_name := decodeString(param_name)
	_param_value := decodeString(param_value)
	v.Header(_param_name, _param_value)
}

// skipped method RequestBuilder.Post2 with unsupported parameter or return types

// skipped method RequestBuilder.Post4 with unsupported parameter or return types

// skipped method RequestBuilder.PostData with unsupported parameter or return types

//export proxyshell_RequestBuilder_PostData2
func proxyshell_RequestBuilder_PostData2(refnum C.int32_t, param_data C.nbyteslice) (C.nbyteslice, C.int32_t) {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*shell.RequestBuilder)
	_param_data := toSlice(param_data, false)
	res_0, res_1 := v.PostData2(_param_data)
	_res_0 := fromSlice(res_0, true)
	var _res_1 C.int32_t = _seq.NullRefNum
	if res_1 != nil {
		_res_1 = C.int32_t(_seq.ToRefNum(res_1))
	}
	return _res_0, _res_1
}

//export proxyshell_RequestBuilder_PostData3
func proxyshell_RequestBuilder_PostData3(refnum C.int32_t, param_data C.nbyteslice) (C.int32_t, C.int32_t) {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*shell.RequestBuilder)
	_param_data := toSlice(param_data, false)
	res_0, res_1 := v.PostData3(_param_data)
	var _res_0 C.int32_t = _seq.NullRefNum
	if res_0 != nil {
		_res_0 = C.int32_t(_seq.ToRefNum(res_0))
	}
	var _res_1 C.int32_t = _seq.NullRefNum
	if res_1 != nil {
		_res_1 = C.int32_t(_seq.ToRefNum(res_1))
	}
	return _res_0, _res_1
}

// skipped method RequestBuilder.PostDirectory with unsupported parameter or return types

// skipped method RequestBuilder.PostReader with unsupported parameter or return types

// skipped method RequestBuilder.PostString with unsupported parameter or return types

//export proxyshell_RequestBuilder_PostString2
func proxyshell_RequestBuilder_PostString2(refnum C.int32_t, param_data C.nstring) (C.nbyteslice, C.int32_t) {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*shell.RequestBuilder)
	_param_data := decodeString(param_data)
	res_0, res_1 := v.PostString2(_param_data)
	_res_0 := fromSlice(res_0, true)
	var _res_1 C.int32_t = _seq.NullRefNum
	if res_1 != nil {
		_res_1 = C.int32_t(_seq.ToRefNum(res_1))
	}
	return _res_0, _res_1
}

//export proxyshell_RequestBuilder_PostString3
func proxyshell_RequestBuilder_PostString3(refnum C.int32_t, param_data C.nstring) (C.int32_t, C.int32_t) {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*shell.RequestBuilder)
	_param_data := decodeString(param_data)
	res_0, res_1 := v.PostString3(_param_data)
	var _res_0 C.int32_t = _seq.NullRefNum
	if res_0 != nil {
		_res_0 = C.int32_t(_seq.ToRefNum(res_0))
	}
	var _res_1 C.int32_t = _seq.NullRefNum
	if res_1 != nil {
		_res_1 = C.int32_t(_seq.ToRefNum(res_1))
	}
	return _res_0, _res_1
}

//export proxyshell_RequestBuilder_Send
func proxyshell_RequestBuilder_Send(refnum C.int32_t) (C.nbyteslice, C.int32_t) {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*shell.RequestBuilder)
	res_0, res_1 := v.Send()
	_res_0 := fromSlice(res_0, true)
	var _res_1 C.int32_t = _seq.NullRefNum
	if res_1 != nil {
		_res_1 = C.int32_t(_seq.ToRefNum(res_1))
	}
	return _res_0, _res_1
}

// skipped method RequestBuilder.Send2 with unsupported parameter or return types

//export proxyshell_RequestBuilder_StringOptions
func proxyshell_RequestBuilder_StringOptions(refnum C.int32_t, param_key C.nstring, param_value C.nstring) {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*shell.RequestBuilder)
	_param_key := decodeString(param_key)
	_param_value := decodeString(param_value)
	v.StringOptions(_param_key, _param_value)
}

//export new_shell_RequestBuilder
func new_shell_RequestBuilder() C.int32_t {
	return C.int32_t(_seq.ToRefNum(new(shell.RequestBuilder)))
}

//export proxyshell_Response_Close
func proxyshell_Response_Close(refnum C.int32_t) C.int32_t {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*shell.Response)
	res_0 := v.Close()
	var _res_0 C.int32_t = _seq.NullRefNum
	if res_0 != nil {
		_res_0 = C.int32_t(_seq.ToRefNum(res_0))
	}
	return _res_0
}

//export proxyshell_Response_Read
func proxyshell_Response_Read(refnum C.int32_t, param_p0 C.nbyteslice) (C.nint, C.int32_t) {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*shell.Response)
	_param_p0 := toSlice(param_p0, false)
	res_0, res_1 := v.Read(_param_p0)
	_res_0 := C.nint(res_0)
	var _res_1 C.int32_t = _seq.NullRefNum
	if res_1 != nil {
		_res_1 = C.int32_t(_seq.ToRefNum(res_1))
	}
	return _res_0, _res_1
}

//export new_shell_Response
func new_shell_Response() C.int32_t {
	return C.int32_t(_seq.ToRefNum(new(shell.Response)))
}

//export proxyshell_Shell_AddDir
func proxyshell_Shell_AddDir(refnum C.int32_t, param_path C.nstring) (C.nstring, C.int32_t) {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*shell.Shell)
	_param_path := decodeString(param_path)
	res_0, res_1 := v.AddDir(_param_path)
	_res_0 := encodeString(res_0)
	var _res_1 C.int32_t = _seq.NullRefNum
	if res_1 != nil {
		_res_1 = C.int32_t(_seq.ToRefNum(res_1))
	}
	return _res_0, _res_1
}

//export proxyshell_Shell_DagPut
func proxyshell_Shell_DagPut(refnum C.int32_t, param_data C.nstring) C.nstring {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*shell.Shell)
	_param_data := decodeString(param_data)
	res_0 := v.DagPut(_param_data)
	_res_0 := encodeString(res_0)
	return _res_0
}

//export proxyshell_Shell_NewRequest
func proxyshell_Shell_NewRequest(refnum C.int32_t, param_command C.nstring) C.int32_t {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*shell.Shell)
	_param_command := decodeString(param_command)
	res_0 := v.NewRequest(_param_command)
	var _res_0 C.int32_t = _seq.NullRefNum
	if res_0 != nil {
		_res_0 = C.int32_t(_seq.ToRefNum(res_0))
	}
	return _res_0
}

//export proxyshell_Shell_WriteStuff
func proxyshell_Shell_WriteStuff(refnum C.int32_t, param_data C.nbyteslice, param_path C.nstring) {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*shell.Shell)
	_param_data := toSlice(param_data, false)
	_param_path := decodeString(param_path)
	v.WriteStuff(_param_data, _param_path)
}

//export new_shell_Shell
func new_shell_Shell() C.int32_t {
	return C.int32_t(_seq.ToRefNum(new(shell.Shell)))
}

//export proxyshell__NewShell
func proxyshell__NewShell(param_url C.nstring) C.int32_t {
	_param_url := decodeString(param_url)
	res_0 := shell.NewShell(_param_url)
	var _res_0 C.int32_t = _seq.NullRefNum
	if res_0 != nil {
		_res_0 = C.int32_t(_seq.ToRefNum(res_0))
	}
	return _res_0
}

//export proxyshell__NewTCPShell
func proxyshell__NewTCPShell(param_port C.nstring) C.int32_t {
	_param_port := decodeString(param_port)
	res_0 := shell.NewTCPShell(_param_port)
	var _res_0 C.int32_t = _seq.NullRefNum
	if res_0 != nil {
		_res_0 = C.int32_t(_seq.ToRefNum(res_0))
	}
	return _res_0
}

//export proxyshell__NewUDSShell
func proxyshell__NewUDSShell(param_sockpath C.nstring) C.int32_t {
	_param_sockpath := decodeString(param_sockpath)
	res_0 := shell.NewUDSShell(_param_sockpath)
	var _res_0 C.int32_t = _seq.NullRefNum
	if res_0 != nil {
		_res_0 = C.int32_t(_seq.ToRefNum(res_0))
	}
	return _res_0
}
