// Code generated by gobind. DO NOT EDIT.

// JNI functions for the Go <=> Java bridge.
//
//   autogenerated by gobind -lang=java -javapkg=danbroid.kipfs command-line-arguments

#include <android/log.h>
#include <stdint.h>
#include "seq.h"
#include "_cgo_export.h"
#include "shell.h"

jclass proxy_class_shell_RequestBuilder;
jmethodID proxy_class_shell_RequestBuilder_cons;
jclass proxy_class_shell_Response;
jmethodID proxy_class_shell_Response_cons;
jclass proxy_class_shell_Shell;
jmethodID proxy_class_shell_Shell_cons;

JNIEXPORT void JNICALL
Java_danbroid_kipfs_shell_Shell__1init(JNIEnv *env, jclass _unused) {
	jclass clazz;
	clazz = (*env)->FindClass(env, "danbroid/kipfs/shell/RequestBuilder");
	proxy_class_shell_RequestBuilder = (*env)->NewGlobalRef(env, clazz);
	proxy_class_shell_RequestBuilder_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "danbroid/kipfs/shell/Response");
	proxy_class_shell_Response = (*env)->NewGlobalRef(env, clazz);
	proxy_class_shell_Response_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "danbroid/kipfs/shell/Shell_");
	proxy_class_shell_Shell = (*env)->NewGlobalRef(env, clazz);
	proxy_class_shell_Shell_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
}

JNIEXPORT jobject JNICALL
Java_danbroid_kipfs_shell_Shell_newShell(JNIEnv* env, jclass _clazz, jstring url) {
	nstring _url = go_seq_from_java_string(env, url);
	int32_t r0 = proxyshell__NewShell(_url);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class_shell_Shell, proxy_class_shell_Shell_cons);
	return _r0;
}

JNIEXPORT jobject JNICALL
Java_danbroid_kipfs_shell_Shell_newTCPShell(JNIEnv* env, jclass _clazz, jstring port) {
	nstring _port = go_seq_from_java_string(env, port);
	int32_t r0 = proxyshell__NewTCPShell(_port);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class_shell_Shell, proxy_class_shell_Shell_cons);
	return _r0;
}

JNIEXPORT jobject JNICALL
Java_danbroid_kipfs_shell_Shell_newUDSShell(JNIEnv* env, jclass _clazz, jstring sockpath) {
	nstring _sockpath = go_seq_from_java_string(env, sockpath);
	int32_t r0 = proxyshell__NewUDSShell(_sockpath);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class_shell_Shell, proxy_class_shell_Shell_cons);
	return _r0;
}

JNIEXPORT jint JNICALL
Java_danbroid_kipfs_shell_RequestBuilder__1_1New(JNIEnv *env, jclass clazz) {
	return new_shell_RequestBuilder();
}

JNIEXPORT void JNICALL
Java_danbroid_kipfs_shell_RequestBuilder_argument(JNIEnv* env, jobject __this__, jstring arg) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _arg = go_seq_from_java_string(env, arg);
	proxyshell_RequestBuilder_Argument(o, _arg);
}

JNIEXPORT void JNICALL
Java_danbroid_kipfs_shell_RequestBuilder_bodyBytes(JNIEnv* env, jobject __this__, jbyteArray body) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nbyteslice _body = go_seq_from_java_bytearray(env, body, 0);
	proxyshell_RequestBuilder_BodyBytes(o, _body);
	go_seq_release_byte_array(env, body, _body.ptr);
}

JNIEXPORT void JNICALL
Java_danbroid_kipfs_shell_RequestBuilder_bodyString(JNIEnv* env, jobject __this__, jstring body) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _body = go_seq_from_java_string(env, body);
	proxyshell_RequestBuilder_BodyString(o, _body);
}

JNIEXPORT void JNICALL
Java_danbroid_kipfs_shell_RequestBuilder_boolOptions(JNIEnv* env, jobject __this__, jstring key, jboolean value) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _key = go_seq_from_java_string(env, key);
	char _value = (char)value;
	proxyshell_RequestBuilder_BoolOptions(o, _key, _value);
}

JNIEXPORT void JNICALL
Java_danbroid_kipfs_shell_RequestBuilder_byteOptions(JNIEnv* env, jobject __this__, jstring key, jbyteArray value) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _key = go_seq_from_java_string(env, key);
	nbyteslice _value = go_seq_from_java_bytearray(env, value, 0);
	proxyshell_RequestBuilder_ByteOptions(o, _key, _value);
	go_seq_release_byte_array(env, value, _value.ptr);
}

JNIEXPORT void JNICALL
Java_danbroid_kipfs_shell_RequestBuilder_header(JNIEnv* env, jobject __this__, jstring name, jstring value) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _name = go_seq_from_java_string(env, name);
	nstring _value = go_seq_from_java_string(env, value);
	proxyshell_RequestBuilder_Header(o, _name, _value);
}

// skipped function RequestBuilder.Post2 with unsupported parameter or return types

// skipped function RequestBuilder.Post4 with unsupported parameter or return types

// skipped function RequestBuilder.PostData with unsupported parameter or return types

JNIEXPORT jbyteArray JNICALL
Java_danbroid_kipfs_shell_RequestBuilder_postData2(JNIEnv* env, jobject __this__, jbyteArray data) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nbyteslice _data = go_seq_from_java_bytearray(env, data, 0);
	struct proxyshell_RequestBuilder_PostData2_return res = proxyshell_RequestBuilder_PostData2(o, _data);
	go_seq_release_byte_array(env, data, _data.ptr);
	jbyteArray _r0 = go_seq_to_java_bytearray(env, res.r0, 1);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT jobject JNICALL
Java_danbroid_kipfs_shell_RequestBuilder_postData3(JNIEnv* env, jobject __this__, jbyteArray data) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nbyteslice _data = go_seq_from_java_bytearray(env, data, 0);
	struct proxyshell_RequestBuilder_PostData3_return res = proxyshell_RequestBuilder_PostData3(o, _data);
	go_seq_release_byte_array(env, data, _data.ptr);
	jobject _r0 = go_seq_from_refnum(env, res.r0, proxy_class_shell_Response, proxy_class_shell_Response_cons);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

// skipped function RequestBuilder.PostDirectory with unsupported parameter or return types

// skipped function RequestBuilder.PostReader with unsupported parameter or return types

// skipped function RequestBuilder.PostString with unsupported parameter or return types

JNIEXPORT jbyteArray JNICALL
Java_danbroid_kipfs_shell_RequestBuilder_postString2(JNIEnv* env, jobject __this__, jstring data) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _data = go_seq_from_java_string(env, data);
	struct proxyshell_RequestBuilder_PostString2_return res = proxyshell_RequestBuilder_PostString2(o, _data);
	jbyteArray _r0 = go_seq_to_java_bytearray(env, res.r0, 1);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT jobject JNICALL
Java_danbroid_kipfs_shell_RequestBuilder_postString3(JNIEnv* env, jobject __this__, jstring data) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _data = go_seq_from_java_string(env, data);
	struct proxyshell_RequestBuilder_PostString3_return res = proxyshell_RequestBuilder_PostString3(o, _data);
	jobject _r0 = go_seq_from_refnum(env, res.r0, proxy_class_shell_Response, proxy_class_shell_Response_cons);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT jbyteArray JNICALL
Java_danbroid_kipfs_shell_RequestBuilder_send(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	struct proxyshell_RequestBuilder_Send_return res = proxyshell_RequestBuilder_Send(o);
	jbyteArray _r0 = go_seq_to_java_bytearray(env, res.r0, 1);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

// skipped function RequestBuilder.Send2 with unsupported parameter or return types

JNIEXPORT void JNICALL
Java_danbroid_kipfs_shell_RequestBuilder_stringOptions(JNIEnv* env, jobject __this__, jstring key, jstring value) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _key = go_seq_from_java_string(env, key);
	nstring _value = go_seq_from_java_string(env, value);
	proxyshell_RequestBuilder_StringOptions(o, _key, _value);
}

JNIEXPORT jint JNICALL
Java_danbroid_kipfs_shell_Response__1_1New(JNIEnv *env, jclass clazz) {
	return new_shell_Response();
}

JNIEXPORT void JNICALL
Java_danbroid_kipfs_shell_Response_close(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	int32_t r0 = proxyshell_Response_Close(o);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT jlong JNICALL
Java_danbroid_kipfs_shell_Response_read(JNIEnv* env, jobject __this__, jbyteArray p0) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nbyteslice _p0 = go_seq_from_java_bytearray(env, p0, 0);
	struct proxyshell_Response_Read_return res = proxyshell_Response_Read(o, _p0);
	go_seq_release_byte_array(env, p0, _p0.ptr);
	jlong _r0 = (jlong)res.r0;
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT jint JNICALL
Java_danbroid_kipfs_shell_Shell_1__1_1NewShell(JNIEnv *env, jclass clazz, jstring url) {
	nstring _url = go_seq_from_java_string(env, url);
	int32_t refnum = proxyshell__NewShell(_url);
	return refnum;
}

JNIEXPORT jstring JNICALL
Java_danbroid_kipfs_shell_Shell_1_addDir(JNIEnv* env, jobject __this__, jstring path) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _path = go_seq_from_java_string(env, path);
	struct proxyshell_Shell_AddDir_return res = proxyshell_Shell_AddDir(o, _path);
	jstring _r0 = go_seq_to_java_string(env, res.r0);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT jstring JNICALL
Java_danbroid_kipfs_shell_Shell_1_dagPut(JNIEnv* env, jobject __this__, jstring data) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _data = go_seq_from_java_string(env, data);
	nstring r0 = proxyshell_Shell_DagPut(o, _data);
	jstring _r0 = go_seq_to_java_string(env, r0);
	return _r0;
}

JNIEXPORT jobject JNICALL
Java_danbroid_kipfs_shell_Shell_1_newRequest(JNIEnv* env, jobject __this__, jstring command) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _command = go_seq_from_java_string(env, command);
	int32_t r0 = proxyshell_Shell_NewRequest(o, _command);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class_shell_RequestBuilder, proxy_class_shell_RequestBuilder_cons);
	return _r0;
}

JNIEXPORT void JNICALL
Java_danbroid_kipfs_shell_Shell_1_writeStuff(JNIEnv* env, jobject __this__, jbyteArray data, jstring path) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nbyteslice _data = go_seq_from_java_bytearray(env, data, 0);
	nstring _path = go_seq_from_java_string(env, path);
	proxyshell_Shell_WriteStuff(o, _data, _path);
	go_seq_release_byte_array(env, data, _data.ptr);
}

