// Code generated by gobind. DO NOT EDIT.

// JNI function headers for the Go <=> Java bridge.
//
//   autogenerated by gobind -lang=java -javapkg=danbroid.kipfs command-line-arguments

#ifndef __Shell_H__
#define __Shell_H__

#include <jni.h>

extern jclass proxy_class_shell_RequestBuilder;
extern jmethodID proxy_class_shell_RequestBuilder_cons;
extern jclass proxy_class_shell_Response;
extern jmethodID proxy_class_shell_Response_cons;
extern jclass proxy_class_shell_Shell;
extern jmethodID proxy_class_shell_Shell_cons;
#endif
