// Code generated by gobind. DO NOT EDIT.

// Java class danbroid.kipfs.shell.RequestBuilder is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=danbroid.kipfs command-line-arguments
package danbroid.kipfs.shell;

import go.Seq;

public final class RequestBuilder implements Seq.Proxy {
	static { Shell.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	RequestBuilder(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public RequestBuilder() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public native void argument(String arg);
	public native void bodyBytes(byte[] body);
	public native void bodyString(String body);
	public native void boolOptions(String key, boolean value);
	public native void byteOptions(String key, byte[] value);
	public native void header(String name, String value);
	// skipped method RequestBuilder.Post2 with unsupported parameter or return types
	
	// skipped method RequestBuilder.Post4 with unsupported parameter or return types
	
	// skipped method RequestBuilder.PostData with unsupported parameter or return types
	
	public native byte[] postData2(byte[] data) throws Exception;
	public native Response postData3(byte[] data) throws Exception;
	// skipped method RequestBuilder.PostDirectory with unsupported parameter or return types
	
	// skipped method RequestBuilder.PostReader with unsupported parameter or return types
	
	// skipped method RequestBuilder.PostString with unsupported parameter or return types
	
	public native byte[] postString2(String data) throws Exception;
	public native Response postString3(String data) throws Exception;
	public native byte[] send() throws Exception;
	// skipped method RequestBuilder.Send2 with unsupported parameter or return types
	
	public native void stringOptions(String key, String value);
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof RequestBuilder)) {
		    return false;
		}
		RequestBuilder that = (RequestBuilder)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("RequestBuilder").append("{");
		return b.append("}").toString();
	}
}

