// Code generated by gobind. DO NOT EDIT.

// Java class danbroid.kipfs.shell.Shell is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=danbroid.kipfs command-line-arguments
package danbroid.kipfs.shell;

import go.Seq;

public abstract class Shell {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Shell() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	
	public static native Shell_ newShell(String url);
	public static native Shell_ newTCPShell(String port);
	/**
	 * NewUDSShell New unix socket domain shell
	 */
	public static native Shell_ newUDSShell(String sockpath);
}
