// Code generated by gobind. DO NOT EDIT.

// Java class danbroid.kipfs.shell.Shell_ is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=danbroid.kipfs command-line-arguments
package danbroid.kipfs.shell;

import go.Seq;

public final class Shell_ implements Seq.Proxy {
	static { Shell.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	public Shell_(String url) {
		this.refnum = __NewShell(url);
		Seq.trackGoRef(refnum, this);
	}
	
	private static native int __NewShell(String url);
	
	Shell_(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public native String addDir(String path) throws Exception;
	public native String dagPut(String data);
	public native RequestBuilder newRequest(String command);
	public native void writeStuff(byte[] data, String path);
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof Shell_)) {
		    return false;
		}
		Shell_ that = (Shell_)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("Shell_").append("{");
		return b.append("}").toString();
	}
}

