// Code generated by gobind. DO NOT EDIT.

// Java class go.error is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=danbroid.kipfs 
package go;

import go.Seq;

public interface error {
	public String error();
	
}

