#!/bin/bash

cd $(dirname $0) && cd ..

while :;  do 

rsync -avSHx --delete --exclude=.idea --exclude='**/build/' --exclude=local.properties  \
	--exclude=tmp --exclude=openssl/src/openssl.git  --exclude='**/.gradle/' \
	 --exclude=.git --exclude=openssl/lib/macosX64 --exclude=openssl/lib \
 ./ mac:~/workspace/kipfs/ 

sleep 1

inotifywait --exclude /build/ --exclude /tmp/ -e modify,delete,move,create  -r . 

done


